export default {
  SHIFT_UPDATE: 'SHIFT_UPDATE',
  CIPHERTEXT_UPDATE: 'CIPHERTEXT_UPDATE',
  CIPHERTEXT_ENCRYPT: 'CIPHERTEXT_ENCRYPT',
  PLAINTEXT_UPDATE: 'PLAINTEXT_UPDATE',
  PLAINTEXT_DECRYPT: 'PLAINTEXT_DECRYPT',
};
